name: Build Typst document
on: push

jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - run: touch main.txt
      - run: ls
      - run: ls ..
      - run: ls ../..
      - run: ls ../../..
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ
      - run: ls